<?php

namespace Database\Seeders;

use App\Models\HtmlKidStage;
use Illuminate\Database\Seeder;

class HtmlKidStageSeeder extends Seeder
{
    public function run(): void
    {
        HtmlKidStage::truncate();

        HtmlKidStage::insert([
            [
                'game_id' => 4,
                'name' => 'Big Title',
                'description' => 'Learn the h1 tag.',
                'order' => 1,
                'content' => 'Create a big title.',
                'timer_seconds' => 60,
                'xp_reward' => 20,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a big title that says Hello!',
                    'hint' => 'Use <h1> for the biggest title.',
                    'keywords' => ['<h1>', '</h1>', 'Hello!'],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>Hello!</h1>',
                    'expectedPreview' => '<h1>Hello!</h1>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Paragraph',
                'description' => 'Learn the p tag.',
                'order' => 2,
                'content' => 'Create a title and paragraph.',
                'timer_seconds' => 75,
                'xp_reward' => 25,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a title and a paragraph.',
                    'hint' => 'Use <p> for normal text.',
                    'keywords' => ['<h1>', '</h1>', '<p>', '</p>', 'My Website', 'Welcome!'],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>My Website</h1><p>Welcome!</p>',
                    'expectedPreview' => '<h1>My Website</h1><p>Welcome!</p>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Cat Image',
                'description' => 'Learn the img tag.',
                'order' => 3,
                'content' => 'Display a cat image.',
                'timer_seconds' => 90,
                'xp_reward' => 30,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a title and display the cat image.',
                    'hint' => 'Use <img src="cat.png"> to show the cat.',
                    'keywords' => ['<h1>', '</h1>', '<img src="cat.png">', 'My Cat'],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>My Cat</h1><img src="cat.png">',
                    'expectedPreview' => '<h1>My Cat</h1><img src="cat.png">',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Cat With Text',
                'description' => 'Use h1, img and p.',
                'order' => 4,
                'content' => 'Add text under the cat.',
                'timer_seconds' => 100,
                'xp_reward' => 35,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a cat page with a title, image and text.',
                    'hint' => 'Use <h1>, <img> and <p>.',
                    'keywords' => ['<h1>', '</h1>', '<img src="cat.png">', '<p>', '</p>', 'My Cat', 'I love cats.'],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>My Cat</h1><img src="cat.png"><p>I love cats.</p>',
                    'expectedPreview' => '<h1>My Cat</h1><img src="cat.png"><p>I love cats.</p>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Small Titles',
                'description' => 'Learn h2 and h3.',
                'order' => 5,
                'content' => 'Create different title sizes.',
                'timer_seconds' => 100,
                'xp_reward' => 40,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create three titles with different sizes.',
                    'hint' => '<h1> is biggest, <h2> is smaller, <h3> is smaller again.',
                    'keywords' => ['<h1>', '</h1>', '<h2>', '</h2>', '<h3>', '</h3>', 'Animals', 'Cat', 'Small Cat'],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>Animals</h1><h2>Cat</h2><h3>Small Cat</h3>',
                    'expectedPreview' => '<h1>Animals</h1><h2>Cat</h2><h3>Small Cat</h3>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Bold Word',
                'description' => 'Learn strong.',
                'order' => 6,
                'content' => 'Make one word important.',
                'timer_seconds' => 100,
                'xp_reward' => 45,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Make the word Cat bold.',
                    'hint' => 'Use <strong> to make important text bold.',
                    'keywords' => ['<p>', '</p>', '<strong>', '</strong>', 'I have a ', 'Cat'],
                    'defaultCode' => '',
                    'expectedCode' => '<p>I have a <strong>Cat</strong></p>',
                    'expectedPreview' => '<p>I have a <strong>Cat</strong></p>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Italic Word',
                'description' => 'Learn em.',
                'order' => 7,
                'content' => 'Make one word italic.',
                'timer_seconds' => 100,
                'xp_reward' => 45,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Make the word soft italic.',
                    'hint' => 'Use <em> for emphasized text.',
                    'keywords' => ['<p>', '</p>', '<em>', '</em>', 'My cat is ', 'soft'],
                    'defaultCode' => '',
                    'expectedCode' => '<p>My cat is <em>soft</em></p>',
                    'expectedPreview' => '<p>My cat is <em>soft</em></p>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'New Line',
                'description' => 'Learn br.',
                'order' => 8,
                'content' => 'Put words on two lines.',
                'timer_seconds' => 90,
                'xp_reward' => 45,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Put Hello and Cat on separate lines.',
                    'hint' => 'Use <br> to create a new line.',
                    'keywords' => ['Hello', '<br>', 'Cat'],
                    'defaultCode' => '',
                    'expectedCode' => 'Hello<br>Cat',
                    'expectedPreview' => 'Hello<br>Cat',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Separator',
                'description' => 'Learn hr.',
                'order' => 9,
                'content' => 'Separate title and text.',
                'timer_seconds' => 90,
                'xp_reward' => 50,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a title, a line, and a paragraph.',
                    'hint' => 'Use <hr> to draw a horizontal line.',
                    'keywords' => ['<h1>', '</h1>', '<hr>', '<p>', '</p>', 'Cat Page', 'Welcome!'],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>Cat Page</h1><hr><p>Welcome!</p>',
                    'expectedPreview' => '<h1>Cat Page</h1><hr><p>Welcome!</p>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Link',
                'description' => 'Learn a and href.',
                'order' => 10,
                'content' => 'Create a link.',
                'timer_seconds' => 100,
                'xp_reward' => 55,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a link that says Visit.',
                    'hint' => 'Use <a href="#">Visit</a>.',
                    'keywords' => ['<a href="#">', '</a>', 'Visit'],
                    'defaultCode' => '',
                    'expectedCode' => '<a href="#">Visit</a>',
                    'expectedPreview' => '<a href="#">Visit</a>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Animal List',
                'description' => 'Learn ul and li.',
                'order' => 11,
                'content' => 'Create a bullet list.',
                'timer_seconds' => 120,
                'xp_reward' => 60,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a list with Cat and Dog.',
                    'hint' => '<ul> creates a list. <li> creates one item.',
                    'keywords' => ['<ul>', '</ul>', '<li>', '</li>', 'Cat', 'Dog'],
                    'defaultCode' => '',
                    'expectedCode' => '<ul><li>Cat</li><li>Dog</li></ul>',
                    'expectedPreview' => '<ul><li>Cat</li><li>Dog</li></ul>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Number List',
                'description' => 'Learn ol.',
                'order' => 12,
                'content' => 'Create a numbered list.',
                'timer_seconds' => 120,
                'xp_reward' => 60,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a numbered list with Apple and Banana.',
                    'hint' => '<ol> creates a numbered list.',
                    'keywords' => ['<ol>', '</ol>', '<li>', '</li>', 'Apple', 'Banana'],
                    'defaultCode' => '',
                    'expectedCode' => '<ol><li>Apple</li><li>Banana</li></ol>',
                    'expectedPreview' => '<ol><li>Apple</li><li>Banana</li></ol>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Animal Card',
                'description' => 'Learn div.',
                'order' => 13,
                'content' => 'Create a simple card.',
                'timer_seconds' => 130,
                'xp_reward' => 65,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a card with a title and paragraph.',
                    'hint' => 'Use <div> to group elements together.',
                    'keywords' => ['<div>', '</div>', '<h2>', '</h2>', '<p>', '</p>', 'Cat', 'Small animal'],
                    'defaultCode' => '',
                    'expectedCode' => '<div><h2>Cat</h2><p>Small animal</p></div>',
                    'expectedPreview' => '<div style="border:2px solid #f97316;border-radius:16px;padding:16px;"><h2>Cat</h2><p>Small animal</p></div>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Button',
                'description' => 'Learn button.',
                'order' => 14,
                'content' => 'Create a button.',
                'timer_seconds' => 100,
                'xp_reward' => 65,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a button that says Click me.',
                    'hint' => 'Use <button> for clickable buttons.',
                    'keywords' => ['<button>', '</button>', 'Click me'],
                    'defaultCode' => '',
                    'expectedCode' => '<button>Click me</button>',
                    'expectedPreview' => '<button style="padding:12px 20px;border-radius:12px;background:#f97316;color:white;border:none;">Click me</button>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Input',
                'description' => 'Learn input.',
                'order' => 15,
                'content' => 'Create a name input.',
                'timer_seconds' => 120,
                'xp_reward' => 70,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create an input with placeholder Your name.',
                    'hint' => 'Use placeholder to show helper text inside input.',
                    'keywords' => ['<input placeholder="Your name">'],
                    'defaultCode' => '',
                    'expectedCode' => '<input placeholder="Your name">',
                    'expectedPreview' => '<input placeholder="Your name" style="padding:12px;border-radius:10px;border:1px solid #ccc;">',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Form',
                'description' => 'Learn form and label.',
                'order' => 16,
                'content' => 'Create a small form.',
                'timer_seconds' => 150,
                'xp_reward' => 75,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a form with label, input and button.',
                    'hint' => '<form> groups fields. <label> describes an input.',
                    'keywords' => ['<form>', '</form>', '<label>', '</label>', '<input>', '<button>', '</button>', 'Name', 'Send'],
                    'defaultCode' => '',
                    'expectedCode' => '<form><label>Name</label><input><button>Send</button></form>',
                    'expectedPreview' => '<form><label>Name</label><br><input style="margin:8px 0;padding:8px;"><br><button>Send</button></form>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Table',
                'description' => 'Learn table, tr and td.',
                'order' => 17,
                'content' => 'Create a simple table.',
                'timer_seconds' => 160,
                'xp_reward' => 80,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a table with Cat and Dog.',
                    'hint' => '<tr> is a row. <td> is a cell.',
                    'keywords' => ['<table>', '</table>', '<tr>', '</tr>', '<td>', '</td>', 'Cat', 'Dog'],
                    'defaultCode' => '',
                    'expectedCode' => '<table><tr><td>Cat</td><td>Dog</td></tr></table>',
                    'expectedPreview' => '<table border="1" cellpadding="12"><tr><td>Cat</td><td>Dog</td></tr></table>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Cat Profile',
                'description' => 'Build a complete animal card.',
                'order' => 18,
                'content' => 'Use div, title, image and paragraph.',
                'timer_seconds' => 180,
                'xp_reward' => 90,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a complete cat profile card.',
                    'hint' => 'Combine <div>, <h2>, <img> and <p>.',
                    'keywords' => ['<div>', '</div>', '<h2>', '</h2>', '<img src="cat.png">', '<p>', '</p>', 'My Cat', 'I love cats.'],
                    'defaultCode' => '',
                    'expectedCode' => '<div><h2>My Cat</h2><img src="cat.png"><p>I love cats.</p></div>',
                    'expectedPreview' => '<div style="border:2px solid #ec4899;border-radius:18px;padding:16px;text-align:center;"><h2>My Cat</h2><img src="cat.png"><p>I love cats.</p></div>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Full HTML Page',
                'description' => 'Learn html, head and body.',
                'order' => 19,
                'content' => 'Create a real HTML page structure.',
                'timer_seconds' => 220,
                'xp_reward' => 100,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a full HTML page with title and body.',
                    'hint' => 'A full page has <html>, <head>, <title> and <body>.',
                    'keywords' => ['<html>', '</html>', '<head>', '</head>', '<title>', '</title>', '<body>', '</body>', '<h1>', '</h1>', 'My Page', 'Hello'],
                    'defaultCode' => '',
                    'expectedCode' => '<html><head><title>My Page</title></head><body><h1>Hello</h1></body></html>',
                    'expectedPreview' => '<h1>Hello</h1>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'game_id' => 4,
                'name' => 'Final Mini Website',
                'description' => 'Use many HTML tags together.',
                'order' => 20,
                'content' => 'Build your final mini website.',
                'timer_seconds' => 300,
                'xp_reward' => 150,
                'is_active' => true,
                'config' => json_encode([
                    'goal' => 'Create a mini website about cats.',
                    'hint' => 'Use title, paragraph, image, list and button.',
                    'keywords' => [
                        '<h1>', '</h1>', '<p>', '</p>', '<img src="cat.png">',
                        '<ul>', '</ul>', '<li>', '</li>', '<button>', '</button>',
                        'Cats', 'Welcome to my cat website.', 'Cute', 'Smart', 'Play'
                    ],
                    'defaultCode' => '',
                    'expectedCode' => '<h1>Cats</h1><p>Welcome to my cat website.</p><img src="cat.png"><ul><li>Cute</li><li>Smart</li></ul><button>Play</button>',
                    'expectedPreview' => '<h1>Cats</h1><p>Welcome to my cat website.</p><img src="cat.png"><ul><li>Cute</li><li>Smart</li></ul><button>Play</button>',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}